name: Docs Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  markdown-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Markdown links
        uses: ruzickap/action-my-markdown-link-checker@v1
